USE [master]
GO

/****** Object:  Database [CS2550Tutor]    Script Date: 4/24/2019 8:45:02 PM ******/
CREATE DATABASE [CS2550Tutor]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CS2550Tutor', FILENAME = N'C:\Users\Dung Hong\CS2550Tutor.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CS2550Tutor_log', FILENAME = N'C:\Users\Dung Hong\CS2550Tutor_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [CS2550Tutor] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CS2550Tutor].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CS2550Tutor] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CS2550Tutor] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CS2550Tutor] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CS2550Tutor] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CS2550Tutor] SET ARITHABORT OFF 
GO

ALTER DATABASE [CS2550Tutor] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CS2550Tutor] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CS2550Tutor] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CS2550Tutor] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CS2550Tutor] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CS2550Tutor] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CS2550Tutor] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CS2550Tutor] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CS2550Tutor] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CS2550Tutor] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CS2550Tutor] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CS2550Tutor] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CS2550Tutor] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CS2550Tutor] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CS2550Tutor] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CS2550Tutor] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CS2550Tutor] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CS2550Tutor] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CS2550Tutor] SET  MULTI_USER 
GO

ALTER DATABASE [CS2550Tutor] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CS2550Tutor] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CS2550Tutor] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CS2550Tutor] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CS2550Tutor] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CS2550Tutor] SET QUERY_STORE = OFF
GO

USE [CS2550Tutor]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [CS2550Tutor] SET  READ_WRITE 
GO


